### ISSUE TITLE
Activating an old system version from a not backward compatible one

### ISSUE THREAD

**Issue by niloda** [openBackhaul/backupAndRestore#1]
Suppose system version B is found in 'running' bench, system version A is found in 'standby' bench, and B's configuration (database) breaks backwards compatibility. Suppose we also want to activate system version A, with the actions defined so far in the model we could fall into the following scenarios:

1. if we activated the system version A (in the standby bench) to download its configuration later, it would start with the current configuration B which is incompatible.
2. if we restore configuration for the system version A, the device after reboot would convert the downloaded configuration A in current configuration B (since the running system version does not change after reboot) and the next bench switch leads us to the scenario of the previous point.

To properly handle such a situation, the model should provide a sort of 'download-and-bench-switch' action, with which the device performs a bench switch instead of rebooting. In this way, the action ensures that the system version on the standby bench works with the newly restored configuration A.

**Comment by demx8as6** [comment]
The required action above should Download the latest available configuration for Version A.
- "download-config-and-bench-switch"

Q: is it better to split the one action into two actions.
A: NO! :)

Pre-conditions for a **remote** procedure:
- device must support the feature "downgrade"
- backup configuration file must be available for "SoftwareVersion A"
- device must not go via "factory-default"
- management must be possible directly which means that OAM-IP AND path to the controller must be available using the old configuration
-

**Comment by openBackhaul** [comment]
**Proposal to the 5G-xhaul call on 20th of September 2023:**
This is not a use case for production environments and needs not to be covered by the harmonized management interface.

**Comment by alattoch** [comment]
This is not a standard case, but it could happen if a device is delivered with a newer version than it is released in the Network. 
But this not a  standard case and very device specific. Also down-grade have strict dependency especially when down grading several version backwards.  
Proposal: Not to implement today

**Comment by openBackhaul** [comment]
Issue has just been closed as there is no need for a solution.
